### ISSUE TITLE
expert(x) 

### ISSUE THREAD

**Issue by cecehuang** [SummerRaining/multi_task-learning#1]
E_net = [[expert(x) for expert in sub_expert] for sub_expert in self.E_layer]

这里貌似没有定义expert这个函数啊，如何理解

**Comment by SummerRaining** [comment]
初始化函数中有： self.expert_layer = [Dense(expert_dim,activation = 'relu') for i in range(n_expert)]。根据你自己的实现不同，可以用其他的结构。
